# Generated by Django 2.2.7 on 2019-11-17 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='pre-launch', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_Tenant',
            field=models.BooleanField(default=False, help_text='Designates whether the user an access tenant details and site.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_broker',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a broker.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_landlord',
            field=models.BooleanField(default=False, help_text='Designates whether the user can access landlord details.'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='pre-launch', max_length=255),
            preserve_default=False,
        ),
    ]
