# Generated by Django 2.2.7 on 2019-11-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Anonymous', max_length=255)),
                ('feedback_content', models.TextField()),
                ('feedback_type', models.CharField(max_length=255)),
                ('timeStamp', models.DateTimeField()),
            ],
        ),
    ]
