# Generated by Django 2.2.7 on 2019-11-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='timeStamp',
            new_name='time_stamp',
        ),
    ]
