# Generated by Django 2.2.7 on 2019-11-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20191127_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_type',
            new_name='type',
        ),
    ]
