const INSEMBLE_PURPLE = '#674EA7';
const LIGHT_PURPLE = '#BBAFDB';
const LIGHTEST_PURPLE = '#EEEBF5';
const DETAIL_GREY = '#727272';
const DARK_DETAIL = '#4B4B4B';
const BRIGHT_BLUE = '#0D7EFF';
const RED = '#FF0000';
const DARK_GREEN = '#549848';
const GREEN = '#36DD93';
const LIGHT_GREEN = '#CAF1DF';
export const GREY = '#B2B2B2';

export const DARKER_GREY = '#D3D3D3';

export const WHITE = '#FFFFFF';

export const THEME_COLOR = INSEMBLE_PURPLE;
export const SECONDARY_COLOR = '#8E7BC4';

export const PURPLE = '#6745AD';
export const LIGHTEST_GREY = '#FBFBFB';
export const LIGHT_GREY = '#C5C5C5';
export const MODAL_GREY = '#F7F7F7';

// Text colors
export const TEXT_COLOR = DARK_DETAIL;
export const MUTED_TEXT_COLOR = LIGHT_GREY;
export const RED_TEXT = RED;
export const UNSELECTED_TEXT_COLOR = LIGHT_GREY;
export const DARK_TEXT_COLOR = DETAIL_GREY;
export const GREEN_TEXT = DARK_GREEN;

export const LINK_COLOR = '#0000EE';

export const HEADER_BORDER_COLOR = 'rgba(103,76,167,0.17)';
export const BOTTOM_CARD_COLOR = LIGHTEST_GREY;
export const TEXT_INPUT_BORDER_COLOR = GREY;
export const DISABLED_TEXT_INPUT_BACKGROUND = LIGHTEST_GREY;
export const BUTTON_BORDER_COLOR = DETAIL_GREY;
export const SECONDARY_CHECKBOX = BRIGHT_BLUE;
export const BADGE_COLOR = RED;
export const BORDER_COLOR = LIGHT_GREY;
export const CARD_GREY_HEADER = LIGHTEST_GREY;
export const BACKGROUND_COLOR = LIGHTEST_GREY;
export const PROGRESS_BAR_BACKGROUND = LIGHTEST_PURPLE;
export const BAR_BACKGROUND = LIGHT_PURPLE;
export const BUTTON_TRANSPARENT_TEXT_COLOR = LIGHT_GREY;
export const ALERT_BACKGROUND_COLOR = LIGHTEST_PURPLE;
export const SLIDER_SECONDARY_COLOR = LIGHT_GREY;
export const HOVERED_LIST_ITEM_BG = '#ECE9F6';
export const TAG_BACKGROUND = LIGHTEST_PURPLE;

export const DISABLED_COLOR = GREY;

// Fragmented progress bar colors
export const FRAGMENTED_PROGRESS_BAR_BACKGROUND = LIGHT_GREY;
export const FRAGMENTED_PROGRESS_BAR_PRIMARY_COLOR = GREEN;
export const FRAGMENTED_PROGRESS_BAR_SECONDARY_COLOR = LIGHT_GREEN;

// Icon colors
export const GREEN_ICON = GREEN;
export const GREY_ICON = DETAIL_GREY;
export const LIGHT_GREY_ICON = LIGHT_GREY;

// Filter carousel colors
export const FILTER_CAROUSEL_INDICATOR = LIGHT_GREY;

// Pie chart colors
export const COMMUTE_CHART_COLORS = ['#674EA7CC', '#674EA799', '#674EA766', '#674EA733'];
