import getGroupedMatchingPropertiesByKey from '../getGroupedMatchingPropertiesByKey';
import { TenantMatches_tenantMatches_matchingProperties as MatchingProperties } from '../../generated/TenantMatches';

describe('getGroupedMatchingPropertiesByKey', () => {
  it('should return the correct array of matching properties grouped by spaceId', () => {
    let arr: Array<MatchingProperties> = [
      {
        __typename: 'MatchingProperty',
        propertyId: '1',
        address: '',
        rent: 20,
        sqft: 10,
        type: ['a', 'b'],
        spaceId: '1',
        spaceCondition: [],
        tenantType: [],
        pro: true,
        visible: true,
        lat: '1',
        lng: '1',
        matchValue: 90,
        thumbnail: '',
      },
      {
        __typename: 'MatchingProperty',
        propertyId: '1',
        address: '',
        rent: 20,
        sqft: 10,
        type: ['a', 'b'],
        spaceId: '2',
        spaceCondition: [],
        tenantType: [],
        pro: true,
        visible: true,
        lat: '1',
        lng: '1',
        matchValue: 90,
        thumbnail: '',
      },
      {
        __typename: 'MatchingProperty',
        propertyId: '2',
        address: '',
        rent: 20,
        sqft: 10,
        type: ['a', 'b'],
        spaceId: '2',
        spaceCondition: [],
        tenantType: [],
        pro: true,
        visible: true,
        lat: '1',
        lng: '1',
        matchValue: 90,
        thumbnail: '',
      },
      {
        __typename: 'MatchingProperty',
        propertyId: '3',
        address: '',
        rent: 20,
        sqft: 10,
        type: ['a', 'b'],
        spaceId: '3',
        spaceCondition: [],
        tenantType: [],
        pro: true,
        visible: true,
        lat: '1',
        lng: '1',
        matchValue: 90,
        thumbnail: '',
      },
    ];

    let result = getGroupedMatchingPropertiesByKey(arr, 'propertyId');
    expect(result).toEqual([
      {
        __typename: 'MatchingProperty',
        propertyId: '1',
        address: '',
        rent: 20,
        sqft: 10,
        type: ['a', 'b'],
        spaceIds: ['1', '2'],
        spaceCondition: [],
        tenantType: [],
        pro: true,
        visible: true,
        lat: '1',
        lng: '1',
        matchValue: 90,
      },
      {
        __typename: 'MatchingProperty',
        propertyId: '2',
        address: '',
        rent: 20,
        sqft: 10,
        type: ['a', 'b'],
        spaceIds: ['2'],
        spaceCondition: [],
        tenantType: [],
        pro: true,
        visible: true,
        lat: '1',
        lng: '1',
        matchValue: 90,
      },
      {
        __typename: 'MatchingProperty',
        propertyId: '3',
        address: '',
        rent: 20,
        sqft: 10,
        type: ['a', 'b'],
        spaceIds: ['3'],
        spaceCondition: [],
        tenantType: [],
        pro: true,
        visible: true,
        lat: '1',
        lng: '1',
        matchValue: 90,
      },
    ]);
  });
});
