// AUTH TYPES
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

// SPACE TYPES
export const MAP_LOADING = "MAP_LOADING";
export const MAP_LOADED = "MAP_LOADED";
export const MAP_ERROR = "MAP_ERROR";
export const LOCATION_LOADED = "LOCATION_LOADED";
export const LOCATION_ERROR = "LOCATION_ERROR";
export const LOCATION_LOADING = "LOCATION_LOADING"
