const INSEMBLE_PURPLE = '#674EA7';
const LIGHT_PURPLE = '#BBAFDB';
const LIGHTEST_PURPLE = '#EEEBF5';
const LIGHTEST_GREY = '#FBFBFB';
const LIGHT_GREY = '#C5C5C5';
const DETAIL_GREY = '#727272';
const DARK_DETAIL = '#4B4B4B';
const BRIGHT_BLUE = '#0D7EFF';
const RED = '#FF0000';

export const WHITE = '#FFFFFF';

export const THEME_COLOR = INSEMBLE_PURPLE;
export const TEXT_COLOR = DARK_DETAIL;
export const SECONDARY_COLOR = '#8E7BC4';
export const HEADER_BORDER_COLOR = 'rgba(103,76,167,0.17)';
export const UNSELECTED_TEXT_COLOR = LIGHT_GREY;
export const BOTTOM_CARD_COLOR = LIGHTEST_GREY;
export const TEXT_INPUT_BORDER_COLOR = '#B2B2B2';
export const BUTTON_BORDER_COLOR = DETAIL_GREY;
export const SECONDARY_CHECKBOX = BRIGHT_BLUE;
export const BADGE_COLOR = RED;
export const BORDER_COLOR = LIGHT_GREY;
export const CARD_GREY_HEADER = LIGHTEST_GREY;
export const BACKGROUND_COLOR = LIGHTEST_GREY;
export const PROGRESS_BAR_BACKGROUND = LIGHTEST_PURPLE;
export const BAR_BACKGROUND = LIGHT_PURPLE;
